// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LexingCoFactory.proto

package grpc.services.LexingCoFactory;

public interface BuildReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LexingCo.BuildReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
