// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LexingCoFactory.proto

package grpc.services.LexingCoFactory;

public final class LexingCoFactoryServiceImpl {
  private LexingCoFactoryServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_BuildRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_BuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_BuildReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_BuildReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_RepairRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_RepairRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_RepairReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_RepairReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025LexingCoFactory.proto\022\010LexingCo\"\034\n\014Bui" +
      "ldRequest\022\014\n\004text\030\001 \001(\t\"\032\n\nBuildReply\022\014\n" +
      "\004text\030\002 \001(\t\"\035\n\rRepairRequest\022\014\n\004text\030\003 \001" +
      "(\t\"\033\n\013RepairReply\022\014\n\004text\030\004 \001(\t2\223\001\n\026Lexi" +
      "ngCoFactoryService\022:\n\010buildCar\022\026.LexingC" +
      "o.BuildRequest\032\024.LexingCo.BuildReply\"\000\022=" +
      "\n\trepairCar\022\027.LexingCo.RepairRequest\032\025.L" +
      "exingCo.RepairReply\"\000B=\n\035grpc.services.L" +
      "exingCoFactoryB\032LexingCoFactoryServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LexingCo_BuildRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LexingCo_BuildRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_BuildRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_LexingCo_BuildReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LexingCo_BuildReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_BuildReply_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_LexingCo_RepairRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LexingCo_RepairRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_RepairRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_LexingCo_RepairReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LexingCo_RepairReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_RepairReply_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
