// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LexingCoWarehouse.proto

package grpc.services.LexingCoWarehouse;

public interface FactoryRestockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LexingCo.FactoryRestockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
