// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LexingCoWarehouse.proto

package grpc.services.LexingCoWarehouse;

public final class LexingCoWarehouseServiceImpl {
  private LexingCoWarehouseServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_RestockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_RestockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_RestockReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_RestockReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027LexingCoWarehouse.proto\022\010LexingCo\"\036\n\016R" +
      "estockRequest\022\014\n\004text\030\001 \001(\t\"\034\n\014RestockRe" +
      "ply\022\014\n\004text\030\002 \001(\t2`\n\030LexingCoWarehouseSe" +
      "rvice\022D\n\016restockFactory\022\030.LexingCo.Resto" +
      "ckRequest\032\026.LexingCo.RestockReply\"\000BA\n\037g" +
      "rpc.services.LexingCoWarehouseB\034LexingCo" +
      "WarehouseServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LexingCo_RestockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LexingCo_RestockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_RestockRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_LexingCo_RestockReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LexingCo_RestockReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_RestockReply_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
