// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LexingCoWarehouse.proto

package grpc.services.LexingCoWarehouse;

public final class LexingCoWarehouseServiceImpl {
  private LexingCoWarehouseServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_FactoryRestockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_FactoryRestockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_FactoryRestockReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_FactoryRestockReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027LexingCoWarehouse.proto\022\010LexingCo\"%\n\025F" +
      "actoryRestockRequest\022\014\n\004text\030\001 \001(\t\"#\n\023Fa" +
      "ctoryRestockReply\022\014\n\004text\030\002 \001(\t2\330\001\n\030Lexi" +
      "ngCoWarehouseService\022Z\n\024restockFactorySt" +
      "ream\022\037.LexingCo.FactoryRestockRequest\032\035." +
      "LexingCo.FactoryRestockReply\"\000(\001\022`\n\030repa" +
      "irStockFactoryStream\022\037.LexingCo.FactoryR" +
      "estockRequest\032\035.LexingCo.FactoryRestockR" +
      "eply\"\000(\0010\001BA\n\037grpc.services.LexingCoWare" +
      "houseB\034LexingCoWarehouseServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LexingCo_FactoryRestockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LexingCo_FactoryRestockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_FactoryRestockRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_LexingCo_FactoryRestockReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LexingCo_FactoryRestockReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_FactoryRestockReply_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
