// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LexingCoWarehouse.proto

package grpc.services.LexingCoWarehouse;

public final class LexingCoWarehouseServiceImpl {
  private LexingCoWarehouseServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_FactoryRestockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_FactoryRestockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LexingCo_FactoryRestockReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LexingCo_FactoryRestockReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027LexingCoWarehouse.proto\022\010LexingCo\"%\n\025F" +
      "actoryRestockRequest\022\014\n\004text\030\001 \001(\t\"#\n\023Fa" +
      "ctoryRestockReply\022\014\n\004text\030\002 \001(\t2\254\002\n\030Lexi" +
      "ngCoWarehouseService\022R\n\016restockFactory\022\037" +
      ".LexingCo.FactoryRestockRequest\032\035.Lexing" +
      "Co.FactoryRestockReply\"\000\022Z\n\024restockFacto" +
      "ryStream\022\037.LexingCo.FactoryRestockReques" +
      "t\032\035.LexingCo.FactoryRestockReply\"\000(\001\022`\n\030" +
      "repairStockFactoryStream\022\037.LexingCo.Fact" +
      "oryRestockRequest\032\035.LexingCo.FactoryRest" +
      "ockReply\"\000(\0010\001BA\n\037grpc.services.LexingCo" +
      "WarehouseB\034LexingCoWarehouseServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LexingCo_FactoryRestockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LexingCo_FactoryRestockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_FactoryRestockRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_LexingCo_FactoryRestockReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LexingCo_FactoryRestockReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LexingCo_FactoryRestockReply_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
