// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LexingCoOrdering.proto

package grpc.services.LexingCoOrdering;

public interface WarehouseRestockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LexingCo.WarehouseRestockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
